### ISSUE TITLE
font expander is ignoring "normal" value for font-weight property

### ISSUE THREAD

**Issue by setthase** [kapetan/css-shorthand-expand#1]
`font-weight: normal;` is often used to clear default browser styles for headings and strong tag.
This is a valid shorthand for a font definition:

``` css
font: normal 23px/2 Arial;
```

but trying to expand this one, module is giving a below result:

``` javascript
{
    font-family: '"Arial"',
    font-size: '23px',
    line-height: 2
}
```

instead of expected result:

``` javascript
{
    font-family: '"Arial"',
    font-size: '23px',
    font-weight: 'normal',
    line-height: 2
}
```

This is because of RegEx defined in [font.js, line 58](https://github.com/kapetan/css-shorthand-expand/blob/master/source/font.js#L58) doesn't include word normal.

**Comment by kapetan** [comment]
Fixed in v1.0.1.
