### ISSUE TITLE
!important attribute not expanded properly

### ISSUE THREAD

**Issue by mcamprecios** [kapetan/css-shorthand-expand#12]
Hi, and thanks for the package. Nothing dramatic but I found a small issue: 

I'm using it on an HTML email framework, piped using PostCSS and Gulp, and I just realised that it doesn't expand the "!important" attribute after the main CSS property.

In my case, with margins: 
`margin: 0 auto !important;`

Thanks a lot in advance!

**Comment by kapetan** [comment]
I'm not sure I understand what the issue is. 

```js
const expand = require('css-shorthand-expand')
console.log(expand('margin', '0 auto !important'))
```

Outputs

```
{
  'margin-top': '0 !important',
  'margin-right': 'auto !important',
  'margin-bottom': '0 !important',
  'margin-left': 'auto !important'
}
```

As expected.
